version: '3'

services:
  auth:
    container_name: auth
    build: ./auth
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - db
    volumes:
      - ./auth:/usr/src/app

  movies:
    container_name: movies
    build: ./movies
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
    depends_on:
      - db
      - auth
    volumes:
      - ./movies:/usr/src/app

  reservations:
    container_name: reservations
    build: ./reservations
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
    depends_on:
      - db
      - auth
      - movies
    volumes:
      - ./reservations:/usr/src/app

  db:
    container_name: db
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_DB=${DATABASE_NAME}
  
  redis:
    image: redis:6.2-alpine
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis:/data
  
volumes:
  redis:
    driver: local