version: '3.5'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_DB=${DATABASE_NAME}
    container_name: postgres
    volumes:
      - /var/lib/postgresql/data
    ports:
      - '5432:5432'

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./src:/app/src